---
title: About myself

---

Originally from a city just on the side of Milano, Italy, I initially studied Economics, obtaining a Bachelor's Degree from Bocconi University. As I developed an interest in demography and sociology, I enrolled in a Master's degree in Sociology and Social Research at the University of Trento (Italy). \
I moved to Germany in 2017 to pursue a double degree Master program, and never left.
I obtained my Master degree in 2019 and my Doctoral degree in 2023 from the universities of Bamberg and HU Berlin, respectively.\
Now I live in the north of Bayern in a beautiful historical town, with my partner and two cats.\
\
In my free time, I volunteer at a local bike co-op and enjoy riding my bikes (plural) in the beautiful hills around my home.
\

*download my CV [here](CVEN.pdf){target="_blank"}*\
*Lebenslauf [herunterladen](CVDE.pdf){target="_blank"}*

## Professional skills{#sec-skills}
- Quantitative data analysis, Quantitative analysis of social processes and change
  - Familiar with classic linear and non-linear model
  - Longitudinal data analysis including panel data, event-history analysis, sequence analysis
- Highly skilled in STATA and R programming
- Scientific writing and communication
- Project planning, individual and team-led research, small team management
\
*You can get an idea of my capabilities by looking at my [portfolio](research.qmd) page*

## Work Experience{#sec-exp}

#### From Nov. 2022 to today - Researcher at the Chair for sociology and quantitative analysis of social Change\
Goethe University, Frankfurt am Main\
In my current position, I work as Researcher (Wissenschaflicher Mitarbeiter) on a third-party (Deutsche Forschungsgemeinschaft) funded research project, looking at how the way people feels about the roles men and women play in society influences their family life.\
In a series of papers, I am focusing on family formation, marriage, union dissolution and transition to parenthood as outcomes of this process.

#### From Sept. 2019 to Nov. 2022 - Researcher at the DYNAMICS Graduate Training Program\
Humboldt University of Berlin\
From September 2019, I was working as doctoral researcher as part of the first pilot wave of the DFG-Funded Graduate Training program DYNAMICS, centered on the analysis of the interplay between, demographic change, democratic processes and public policy.\
[Learn more about the program](https://www.sowi.hu-berlin.de/en/dynamics/about-dynamics)


